/**
 * US cities for retirement location selector.
 * Includes state capitals and major metropolitan areas, sorted alphabetically by city name.
 * Format: "City, ST"
 */
export const US_CITIES: string[] = [
  "Abilene, TX",
  "Akron, OH",
  "Albuquerque, NM",
  "Alexandria, VA",
  "Allentown, PA",
  "Amarillo, TX",
  "Anaheim, CA",
  "Anchorage, AK",
  "Ann Arbor, MI",
  "Annapolis, MD",
  "Albany, NY",
  "Arlington, TX",
  "Arlington, VA",
  "Atlanta, GA",
  "Augusta, GA",
  "Augusta, ME",
  "Aurora, CO",
  "Aurora, IL",
  "Austin, TX",
  "Bakersfield, CA",
  "Baltimore, MD",
  "Baton Rouge, LA",
  "Birmingham, AL",
  "Bismarck, ND",
  "Boise, ID",
  "Boston, MA",
  "Bridgeport, CT",
  "Buffalo, NY",
  "Cape Coral, FL",
  "Carlsbad, CA",
  "Carmel, IN",
  "Carson City, NV",
  "Cary, NC",
  "Cedar Rapids, IA",
  "Charleston, SC",
  "Charleston, WV",
  "Charlotte, NC",
  "Chattanooga, TN",
  "Chesapeake, VA",
  "Chicago, IL",
  "Chula Vista, CA",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbia, SC",
  "Columbus, OH",
  "Columbus, GA",
  "Concord, CA",
  "Concord, NH",
  "Dover, DE",
  "Corpus Christi, TX",
  "Dallas, TX",
  "Davenport, IA",
  "Dayton, OH",
  "Denver, CO",
  "Des Moines, IA",
  "Detroit, MI",
  "Durham, NC",
  "El Paso, TX",
  "Elk Grove, CA",
  "Eugene, OR",
  "Evansville, IN",
  "Fairfax, VA",
  "Fargo, ND",
  "Fayetteville, NC",
  "Fort Wayne, IN",
  "Fort Worth, TX",
  "Fresno, CA",
  "Frisco, TX",
  "Garden Grove, CA",
  "Garland, TX",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Grand Prairie, TX",
  "Grand Rapids, MI",
  "Greensboro, NC",
  "Hampton, VA",
  "Harrisburg, PA",
  "Hartford, CT",
  "Helena, MT",
  "Hayward, CA",
  "Henderson, NV",
  "Hialeah, FL",
  "Honolulu, HI",
  "Houston, TX",
  "Huntington Beach, CA",
  "Huntsville, AL",
  "Indianapolis, IN",
  "Irvine, CA",
  "Irving, TX",
  "Jackson, MS",
  "Jacksonville, FL",
  "Jefferson City, MO",
  "Jersey City, NJ",
  "Kansas City, MO",
  "Kansas City, KS",
  "Knoxville, TN",
  "Lafayette, LA",
  "Lakewood, CO",
  "Lancaster, CA",
  "Lansing, MI",
  "Laredo, TX",
  "Las Vegas, NV",
  "Lexington, KY",
  "Lincoln, NE",
  "Little Rock, AR",
  "Frankfort, KY",
  "Long Beach, CA",
  "Los Angeles, CA",
  "Louisville, KY",
  "Lubbock, TX",
  "Madison, WI",
  "Manchester, NH",
  "McAllen, TX",
  "Memphis, TN",
  "Mesa, AZ",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Mobile, AL",
  "Modesto, CA",
  "Montpelier, VT",
  "Montgomery, AL",
  "Moreno Valley, CA",
  "Nashville, TN",
  "New Haven, CT",
  "New Orleans, LA",
  "New York, NY",
  "Newark, NJ",
  "Newport News, VA",
  "Norfolk, VA",
  "North Las Vegas, NV",
  "Oakland, CA",
  "Oklahoma City, OK",
  "Omaha, NE",
  "Orlando, FL",
  "Overland Park, KS",
  "Oxnard, CA",
  "Palm Bay, FL",
  "Palmdale, CA",
  "Pasadena, CA",
  "Pasadena, TX",
  "Paterson, NJ",
  "Pembroke Pines, FL",
  "Peoria, AZ",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pierre, SD",
  "Pittsburgh, PA",
  "Plano, TX",
  "Portland, OR",
  "Providence, RI",
  "Raleigh, NC",
  "Reno, NV",
  "Richmond, VA",
  "Riverside, CA",
  "Rochester, NY",
  "Rockford, IL",
  "Sacramento, CA",
  "Saint Paul, MN",
  "Salem, OR",
  "Salinas, CA",
  "Salt Lake City, UT",
  "San Antonio, TX",
  "San Bernardino, CA",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Santa Ana, CA",
  "Santa Clarita, CA",
  "Santa Rosa, CA",
  "Santa Fe, NM",
  "Savannah, GA",
  "Scottsdale, AZ",
  "Seattle, WA",
  "Shreveport, LA",
  "Sioux Falls, SD",
  "Spokane, WA",
  "Springfield, MA",
  "Springfield, MO",
  "Springfield, IL",
  "St. Louis, MO",
  "St. Petersburg, FL",
  "Stamford, CT",
  "Stockton, CA",
  "Sunnyvale, CA",
  "Syracuse, NY",
  "Tallahassee, FL",
  "Tampa, FL",
  "Tempe, AZ",
  "Thornton, CO",
  "Toledo, OH",
  "Topeka, KS",
  "Torrance, CA",
  "Trenton, NJ",
  "Tucson, AZ",
  "Tulsa, OK",
  "Virginia Beach, VA",
  "Washington, DC",
  "Olympia, WA",
  "Cheyenne, WY",
  "West Valley City, UT",
  "Wichita, KS",
  "Wichita Falls, TX",
  "Winston-Salem, NC",
  "Yonkers, NY",
].sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" }));
